language: php

cache:
  directories:
    - $HOME/.composer/cache

sudo: false

php:
  - 5.6
  - 7.0
  - nightly
  - hhvm

env:
  - DB=mysql
  - DB=pgsql
  - DB=sqlite
  
before_install:
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then phpenv config-rm xdebug.ini; fi
  - composer self-update

install: composer update $COMPOSER_FLAGS --prefer-dist

script: ./vendor/bin/phpunit -c tests/travis/$DB.travis.xml

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: COMPOSER_FLAGS="--prefer-lowest" DB=sqlite
  exclude:
    - php: hhvm
      env: DB=pgsql  # driver for PostgreSQL currently unsupported by HHVM, requires 3rd party dependency
  allow_failures:
    - php: nightly

branches:
  only:
    - master
