language: php

cache:
  directories:
    - $HOME/.composer/cache

sudo: false

php:
  - 5.6
  - 7.0
  - hhvm
  
before_script:
    - composer self-update
    - composer update --prefer-source $COMPOSER_FLAGS 

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: COMPOSER_FLAGS="--prefer-lowest"
  allow_failures:
    - php: hhvm
